name = "GitHubActions"
uuid = "6b79fd1a-b13a-48ab-b6b0-aaee1fee41df"
authors = ["Chris de Graaf <me@cdg.dev> and contributors"]
version = "0.1.8"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
JSON = "0.21"
julia = "1"

[extras]
SimpleMock = "a896ed2c-15a5-4479-b61d-a0e88e2a1d25"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SimpleMock", "Suppressor", "Test"]
